## nginx configuration
## Ref: https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
##
controller:
  admissionWebhooks:
    enabled: false
    patch:
     enabled: false
  hostNetwork: true
  publishService:
    enabled: false
  ## Use host ports 80 and 443
  daemonset:
    useHostPort: false

    hostPorts:
      http: 80
      https: 443

  kind: DaemonSet

  service:
    enabled: false
