k8gb:
  dnsZones:
    - parentZone: "k8gb.io"
      loadBalancedZone: "cloud.k8gb.io"
      dnsZoneNegTTL: 30
  edgeDNSServers:
  - DNS_SERVER_TODO

extdns:
  enabled: true
  provider:
    name: aws
  domainFilters:
  - k8gb.io
  env:
  - name: AWS_DEFAULT_REGION
    value: "us-east-1"
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: .aws/credentials
  extraVolumes:
  - name: aws-credentials
    secret:
      secretName: external-dns-secret-aws
  extraVolumeMounts:
  - name: aws-credentials
    mountPath: /.aws
    readOnly: true
