k8gb:
  imageRepo: "docker.io/absaoss/k8gb"
  deployCrds: true
  deployRbac: true
  # -- dns zone that will be managed by CoreDNS
  dnsZones:
    - loadBalancedZone: "global.k8gb.local" # -- dnsZone controlled by gslb
      parentZone: "k8gb.local" # -- main zone which would contain gslb zone to delegate
      dnsZoneNegTTL: 300 # -- Negative TTL for SOA record
  # -- host/ip[:port] format is supported here where port defaults to 53
  edgeDNSServers:
      # -- use this DNS server as a main resolver to enable cross k8gb DNS based communication
      - "10.10.0.6"
  # -- used for places where we need to distinguish between different Gslb instances
  clusterGeoTag: "uksouth"
  # -- comma-separated list of external gslb geo tags to pair with
  extGslbClustersGeoTags: "francecentral"
  # -- Reconcile time in seconds
  reconcileRequeueSeconds: 30
  log:
    # -- log format (simple,json)
    format: json # log format (simple,json)
    # -- log level (panic,fatal,error,warn,info,debug,trace)
    level: info # log level (panic,fatal,error,warn,info,debug,trace)
  # -- Metrics server address
  metricsAddress: "0.0.0.0:8080"
  securityContext:
    # -- For more options consult https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#securitycontext-v1-core
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsUser: 1000

extdns:
  enabled: true
  fullnameOverride: "k8gb-external-dns"
  provider:
    name: rfc2136
  txtPrefix: "k8gb-uksouth-"
  txtOwnerId: "k8gb-global.k8gb.local-uksouth"
  domainFilters:
    - k8gb.local
  dnsPolicy: ClusterFirst
  env:
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: rfc2136
        key: secret
  extraArgs:
    rfc2136-tsig-axfr:
    rfc2136-tsig-secret-alg: hmac-sha256
    rfc2136-tsig-keyname: externaldns-key
    rfc2136-gss-tsig:
    rfc2136-kerberos-username: k8gb
    rfc2136-kerberos-password: asdfkuj#f8guh1
    rfc2136-kerberos-realm: k8gb.local
    rfc2136-host: dc.k8gb.local
    rfc2136-port: "53"
    rfc2136-zone: k8gb.local
  extraVolumes:
    - name: kerberos-config-volume
      configMap:
        name: kerberos-config-volume
        defaultMode: 420
  extraVolumeMounts:
    - name: kerberos-config-volume
      mountPath: /etc/krb5.conf
      subPath: krb5.conf

coredns:
  # -- service: refer to https://www.k8gb.io/docs/service_upgrade.html for upgrading CoreDNS service steps
  serviceType: LoadBalancer
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
