k8gb:
  reconcileRequeueSeconds: 10
  dnsZones:
    - dnsZoneNegTTL: 10
      loadBalancedZone: cloud.example.com
      parentZone: example.com
  log:
    format: simple
    level: debug
coredns:
  serviceType: LoadBalancer
rfc2136:
  enabled: true
